[[redirects]]
  from = "http://blackrockcivil.net/*"
  to = "https://www.blackrockcivil.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://blackrockcivil.net/*"
  to = "https://www.blackrockcivil.net/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"